[project]
name = "project-liubu"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "anymessage>=0.1.0",
    "langgraph>=0.3.0",
    "python-dotenv>=0.19.0",
]
